import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "./Context/ProductContext";

const poppins = Poppins({
  subsets: ["latin"], 
  weight: ["300"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.className} `} >
        <ProductProvider>
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
